import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';

import { getServerAuthSession } from '~/server/auth';
import MainLayout from '~/components/MainLayout';

export const getServerSideProps: GetServerSideProps = async (ctx) => {
    const session = await getServerAuthSession(ctx);

    if (!session) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            },
        };
    }

    return { props: { session } };
};

const HomePage: NextPage = () => {
    // const hello = api.example.hello.useQuery({ text: 'from tRPC' });

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name='description' content='Generated by create-t3-app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <MainLayout>Main Layout</MainLayout>
        </>
    );
};

export default HomePage;
